// =============================================================================
// sheets.ts — loader + helpers for the curated DSA Sheets data
//
// WHAT THIS IS
// The Sheets feature browses hand-curated lists of popular DSA problem sheets
// (Striver's SDE, Fraz, Blind 75, company-wise PYQs, ...) so a user can add a
// whole curated list to their tracker in one go instead of typing problem
// numbers by hand.
//
// THE DATA LAYOUT
// Generated by `node scripts/generate-sheets-json.mjs` into src/data/sheets/:
//
//   index.json                tiny catalog: one entry per sheet (id, title,
//                             counts). Loaded eagerly by the /sheets listing.
//   <sheet>.json              one file per sheet, containing ONLY LeetCode
//                             problem numbers grouped into the sheet's own
//                             topic sections:
//                               { id, title, sourceUrl, lastVerified,
//                                 problemCount, sectionCount,
//                                 sections: [{ name, items: number[] }] }
//   problems-<sheet>.json     metadata for exactly the problems that sheet
//                             references, keyed by problem number:
//                               { "1": { t, d, s, p } }
//                               t = title, d = difficulty, s = slug,
//                               p = primary topic
//   unresolved.json           source entries that could not be mapped to a
//                             LeetCode problem. Never imported by the app;
//                             documentation for whoever does the manual
//                             mapping of the Love Babbar sheet.
//
// WHY SHEETS HOLD BARE NUMBERS
// The same LeetCode problem appears in many sheets - Two Sum alone is in six of
// them - so storing its metadata per sheet would duplicate it thousands of times
// across 13,900 references. Holding only the number and joining against the
// metadata slice at read time keeps the sheet payload at ~74 KB instead of
// ~370 KB, and leaves exactly one definition of each problem per sheet.
//
// WHY THE METADATA IS SLICED PER SHEET
// A single shared problems.json would be 276 KB on every sheets page, so
// Blind 75 would ship all 2,575 problems to render 69. Sliced per sheet, the
// common sheets cost single-digit KB and only company-pyqs — which genuinely
// references every problem — pays the full cost.
//
// WHY AN EXPLICIT LOADER MAP INSTEAD OF A TEMPLATE-LITERAL IMPORT
// `await import(`@/data/sheets/${slug}.json`)` would need the bundler to
// synthesise a context module for the whole directory. The explicit map below
// keeps each sheet a statically-known, independently-chunked import, which is
// what actually prevents company-pyqs from being pulled into the initial
// payload of every page that touches the sheets loader.
// =============================================================================

// NOTE: there is no shared `Difficulty` type in the codebase. Both
// src/lib/platforms/types.ts and src/lib/scheduling.ts inline the
// 'EASY' | 'MEDIUM' | 'HARD' union, so we do the same rather than
// refactor those modules as a side effect of this feature.

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export type Difficulty = 'EASY' | 'MEDIUM' | 'HARD';

/** One topic section within a sheet, e.g. Striver's "Binary Search". */
export type SheetSection = {
  name: string;
  /** LeetCode problem numbers, in the order the sheet lists them. */
  items: number[];
};

/** A full sheet, as stored in src/data/sheets/<id>.json. */
export type Sheet = {
  id: string;
  title: string;
  description: string;
  sourceUrl: string;
  lastVerified: string;
  problemCount: number;
  sectionCount: number;
  sections: SheetSection[];
};

/**
 * A problem's state inside the signed-in user's tracker.
 *
 * Returned by the progress endpoints so the sheet view can render the same
 * signals the dashboard does — lifecycle status, bookmark, ladder position —
 * without the client having to join against /api/problems.
 */
export type TrackedInfo = {
  /** The Problem row's cuid, needed by PATCH /api/problems/[id]. */
  id: string;
  status: 'ACTIVE' | 'MASTERED' | 'RETIRED';
  isFavorite: boolean;
  currentStep: number;
  revisionCount: number;
};

/** Keyed by LeetCode problem number — these sheets are 100% LeetCode. */
export type TrackedMap = Record<string, TrackedInfo>;

/** A catalog entry, as stored in src/data/sheets/index.json. */
export type SheetSummary = {
  id: string;
  title: string;
  /** One-line summary shown under the sheet name on the /sheets cards. */
  description: string;
  sourceUrl: string;
  problemCount: number;
  sectionCount: number;
};

/** Metadata for a single problem, as stored in src/data/sheets/problems.json. */
export type SheetProblem = {
  /** title */
  t: string;
  /** difficulty */
  d: Difficulty;
  /** slug — the URL is rebuilt from this rather than stored, see lcUrl() */
  s: string;
  /** primary topic (LeetCode lists several; we keep the first) */
  p: string;
  /**
   * Up to three companies known to ask this question, most distinctive first.
   * Optional — a few problems are only tagged by very small companies and get
   * filtered out upstream.
   */
  co?: string[];
};

export type SheetIndex = {
  lastVerified: string;
  sheets: SheetSummary[];
};

/** A problem resolved against the metadata slice, ready to render. */
export type ResolvedProblem = {
  id: number;
  title: string;
  difficulty: Difficulty;
  topic: string;
  url: string;
  /** Companies known to ask this problem, most distinctive first. */
  companies: string[];
};

/** A section with its problems already resolved, ready to render. */
export type SheetSectionResolved = {
  name: string;
  problems: ResolvedProblem[];
};

/**
 * A sheet as returned by getSheet(): the static structure plus the resolved
 * metadata for exactly the problems it references.
 */
export type LoadedSheet = Sheet & {
  problems: Record<number, ResolvedProblem>;
};

// ---------------------------------------------------------------------------
// Static imports
//
// Only the catalog is eager: it is ~1.4 KB and the /sheets listing needs it.
// The per-sheet files and their metadata slices are all lazy — see the loader
// map below.
// ---------------------------------------------------------------------------

import indexJson from '../data/sheets/index.json';

export const SHEET_INDEX = indexJson as unknown as SheetIndex;

// ---------------------------------------------------------------------------
// Per-sheet lazy loaders
//
// Every sheet gets its own two chunks (the sheet itself, plus the metadata for
// exactly the problems it references). The metadata is sliced per sheet rather
// than shared because a single global index would be 276 KB on every sheets
// page — Blind 75 references 69 problems and would ship all 2,575 to render
// them. Sliced, Blind 75 costs ~7 KB and only company-pyqs pays the full price.
//
// Adding a sheet means adding one line here plus one builder in the generator.
// ---------------------------------------------------------------------------

type SheetJson = Sheet;
type SheetProblemsJson = Record<string, SheetProblem>;

/**
 * Import a sheet and its metadata slice together.
 *
 * The casts are needed because TypeScript infers `difficulty` as a plain
 * `string` from JSON modules, which is not assignable to the Difficulty union.
 * The generator is the thing that guarantees the values, so the assertion is
 * made once here rather than at every use site.
 */
async function loadPair(
  sheetImport: () => Promise<unknown>,
  problemsImport: () => Promise<unknown>,
): Promise<[SheetJson, SheetProblemsJson]> {
  const [sheetMod, problemsMod] = await Promise.all([sheetImport(), problemsImport()]);
  return [
    (sheetMod as { default: SheetJson }).default,
    (problemsMod as { default: SheetProblemsJson }).default,
  ];
}

const SHEET_LOADERS: Record<
  string,
  () => Promise<[SheetJson, SheetProblemsJson]>
> = {
  arsh: () =>
    loadPair(
      () => import('../data/sheets/arsh.json'),
      () => import('../data/sheets/problems-arsh.json'),
    ),
  'blind-75': () =>
    loadPair(
      () => import('../data/sheets/blind-75.json'),
      () => import('../data/sheets/problems-blind-75.json'),
    ),
  'company-pyqs': () =>
    loadPair(
      () => import('../data/sheets/company-pyqs.json'),
      () => import('../data/sheets/problems-company-pyqs.json'),
    ),
  fraz: () =>
    loadPair(
      () => import('../data/sheets/fraz.json'),
      () => import('../data/sheets/problems-fraz.json'),
    ),
  'love-babbar-450': () =>
    loadPair(
      () => import('../data/sheets/love-babbar-450.json'),
      () => import('../data/sheets/problems-love-babbar-450.json'),
    ),
  'striver-a2z': () =>
    loadPair(
      () => import('../data/sheets/striver-a2z.json'),
      () => import('../data/sheets/problems-striver-a2z.json'),
    ),
  'striver-sde': () =>
    loadPair(
      () => import('../data/sheets/striver-sde.json'),
      () => import('../data/sheets/problems-striver-sde.json'),
    ),
};

/** Every sheet id the app knows about. */
export const SHEET_IDS = Object.keys(SHEET_LOADERS);

/** Lookup a catalog entry by id. */
export function getSheetSummary(id: string): SheetSummary | null {
  return SHEET_INDEX.sheets.find((s) => s.id === id) ?? null;
}

const sheetCache = new Map<string, LoadedSheet>();

/**
 * Load a full sheet plus the metadata for its problems, or null if the id is
 * unknown.
 *
 * Results are memoised per process: the JSON is immutable at runtime, and
 * company-pyqs is large enough that re-reading it on every request would be
 * wasteful. This mirrors the dataset caching in src/lib/platforms/leetcode.ts.
 */
export async function getSheet(id: string): Promise<LoadedSheet | null> {
  if (sheetCache.has(id)) return sheetCache.get(id)!;

  const loader = SHEET_LOADERS[id];
  if (!loader) return null;

  const [rawSheet, rawProblems] = await loader();
  const problems: Record<number, ResolvedProblem> = {};
  for (const [key, p] of Object.entries(rawProblems as SheetProblemsJson)) {
    problems[Number(key)] = toResolvedProblem(Number(key), p);
  }

  const sheet: LoadedSheet = {
    id: rawSheet.id,
    title: rawSheet.title,
    description: rawSheet.description,
    sourceUrl: rawSheet.sourceUrl,
    lastVerified: rawSheet.lastVerified,
    problemCount: rawSheet.problemCount,
    sectionCount: rawSheet.sectionCount,
    sections: rawSheet.sections.map((s) => ({ name: s.name, items: [...s.items] })),
    problems,
  };

  sheetCache.set(id, sheet);
  return sheet;
}

// ---------------------------------------------------------------------------
// Metadata resolution
// ---------------------------------------------------------------------------

/** Canonical LeetCode URL for a slug. */
export function lcUrl(slug: string): string {
  return `https://leetcode.com/problems/${slug}/`;
}

/**
 * Build a renderable row from the compact stored metadata.
 *
 * The URL is rebuilt from the slug rather than stored: the slug is ~20 chars
 * against a ~45 char URL, which is ~70 KB saved across the full problem set.
 */
export function toResolvedProblem(id: number, p: SheetProblem): ResolvedProblem {
  return {
    id,
    title: p.t,
    difficulty: p.d,
    topic: p.p,
    url: lcUrl(p.s),
    companies: p.co ?? [],
  };
}

/** Resolve one problem number within a loaded sheet, or null if absent. */
export function resolveProblem(
  sheet: Pick<LoadedSheet, 'problems'>,
  id: number,
): ResolvedProblem | null {
  return sheet.problems[id] ?? null;
}

/**
 * The sheet's problems grouped by section, in sheet order, with any problem the
 * metadata slice lacks dropped.
 *
 * Dropping rather than throwing is deliberate: the generator only emits ids it
 * could verify, so a miss means the two files drifted apart. Surfacing that as a
 * crash on a browse page would be worse than rendering 69 of 69 rows.
 */
export function resolveSections(sheet: LoadedSheet): SheetSectionResolved[] {
  return sheet.sections
    .map((s) => ({
      name: s.name,
      problems: s.items
        .map((id) => sheet.problems[id])
        .filter((p): p is ResolvedProblem => p !== undefined),
    }))
    .filter((s) => s.problems.length > 0);
}

/** Every distinct problem in a sheet, de-duplicated, in first-seen order. */
export function sheetProblemIds(sheet: Pick<Sheet, 'sections'>): number[] {
  const seen = new Set<number>();
  const out: number[] = [];
  for (const s of sheet.sections) {
    for (const id of s.items) {
      if (!seen.has(id)) {
        seen.add(id);
        out.push(id);
      }
    }
  }
  return out;
}

// ---------------------------------------------------------------------------
// Query helpers (pure, unit-tested in sheets.test.ts)
// ---------------------------------------------------------------------------

/** Difficulty tallies for a list of resolved problems. */
export function countByDifficulty(
  problems: ResolvedProblem[],
): Record<Difficulty, number> {
  const counts: Record<Difficulty, number> = { EASY: 0, MEDIUM: 0, HARD: 0 };
  for (const p of problems) counts[p.difficulty]++;
  return counts;
}

/**
 * Split problem numbers into the ones already in the user's tracker and the ones
 * still missing.
 *
 * `tracked` is keyed by problem number because these sheets are 100% LeetCode,
 * so the platform never varies within a sheet and the composite unique
 * constraint collapses to the number alone.
 */
export function partitionTracked(
  ids: number[],
  tracked: TrackedMap,
): { added: number[]; missing: number[] } {
  const added: number[] = [];
  const missing: number[] = [];
  for (const id of ids) {
    (tracked[String(id)] ? added : missing).push(id);
  }
  return { added, missing };
}

/** Case-insensitive substring match over a problem's title and topic. */
export function matchesQuery(problem: ResolvedProblem, query: string): boolean {
  const q = query.trim().toLowerCase();
  if (!q) return true;
  return (
    problem.title.toLowerCase().includes(q) || problem.topic.toLowerCase().includes(q)
  );
}

/**
 * Guard for the bulk-add endpoint: how many problems may be added in one call.
 * Matches the ceiling already used by /api/problems/import.
 */
export const MAX_ADD_PER_REQUEST = 1000;
